openapi: 3.0.1
info:
  title: Swagger Docs
  description: 'Description here'
  termsOfService: http://swagger.io/terms/
  contact:
    email: edhi.uchiha@gmail.com
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /notes:
    get:
      responses:
        200:
          description: Get all notes
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      requestBody:
        description: Text of the note we want to save
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Note'
        required: false
      responses:
        201:
          description: Note was correctly created
          content: {}
      x-codegen-request-body-name: note
  /notes/{id}:
    get:
      parameters:
        - name: id
          in: path
          description: Id of the note.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Note was fetched correctly
          content: {}
        404:
          description: Note wasn't found
          content: {}
    put:
      parameters:
        - name: id
          in: path
          description: Id of the note.
          required: true
          schema:
            type: string
      requestBody:
        description: Text of the note we want to save
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Note'
        required: false
      responses:
        200:
          description: Note was replaced.
          content: {}
        500:
          description: Internal server error
          content: {}
      x-codegen-request-body-name: note
    delete:
      parameters:
        - name: id
          in: path
          description: Id of the note.
          required: true
          schema:
            type: string
      responses:
        204:
          description: Note was deleted
          content: {}
        404:
          description: Note missing
          content: {}
      x-codegen-request-body-name: note
    patch:
      parameters:
        - name: id
          in: path
          description: Id of the note.
          required: true
          schema:
            type: string
      requestBody:
        description: Text of the note we want to save
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Note'
        required: false
      responses:
        200:
          description: Note was changed.
          content: {}
        500:
          description: Internal server error
          content: {}
      x-codegen-request-body-name: note
components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: string
          description: The unique ID for the note
        text:
          type: string
          description: The note of the text
